'use strict';

const { initializeApp, getApps } = require('firebase-admin/app');
const { getAuth } = require('firebase-admin/auth');
const { getFirestore } = require('firebase-admin/firestore');
const { onCall, HttpsError } = require('firebase-functions/v2/https');
const { defineSecret, defineBoolean, defineString } = require('firebase-functions/params');
const nodemailer = require('nodemailer');
const { createVerificationService, VerificationError, DOMAIN } = require('./ulsVerification');

if (!getApps().length) initializeApp();
const otpSecret = defineSecret('ULS_OTP_SECRET');
const smtpSecret = defineSecret('ULS_SMTP_CONFIG');
const enabled = defineBoolean('ULS_VERIFICATION_ENABLED', { default: false });
const pilotEmails = defineString('ULS_PILOT_EMAILS', { default: 'araujotiagofc@gmail.com' });
const db = getFirestore();

const options = {
  region: 'europe-west1', memory: '256MiB', timeoutSeconds: 30,
  minInstances: 0, maxInstances: 2, concurrency: 20, invoker: 'public',
  cors: process.env.FUNCTIONS_EMULATOR === 'true'
    ? [/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/]
    : ['https://circ-coimbra.org', 'https://www.circ-coimbra.org'],
};

const store = {
  runTransaction: (run) => db.runTransaction((transaction) => run({
    get: async (path) => { const doc = await transaction.get(db.doc(path)); return doc.exists ? doc.data() : null; },
    set: (path, data) => transaction.set(db.doc(path), data),
  })),
};

function mailSender() {
  let config;
  try { config = JSON.parse(smtpSecret.value()); } catch { throw new HttpsError('unavailable', 'Serviço temporariamente indisponível.'); }
  const port = Number(config.port);
  if (!config.host || ![465, 587].includes(port) || !config.user || !config.pass
      || typeof config.from !== 'string' || !/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(config.from)) {
    throw new HttpsError('unavailable', 'Serviço temporariamente indisponível.');
  }
  const transport = nodemailer.createTransport({
    host: config.host, port, secure: port === 465, requireTLS: true,
    auth: { user: config.user, pass: config.pass },
    tls: { minVersion: 'TLSv1.2', rejectUnauthorized: true },
    connectionTimeout: 8000, greetingTimeout: 8000, socketTimeout: 12000,
    logger: false, debug: false,
  });
  return async ({ to, code }) => {
    // Destination and content are generated by the server; never accept arbitrary mail payloads.
    if (!new RegExp(`^\\d{1,12}@${DOMAIN.replace(/\./g, '\\.')}\u0024`).test(to)) throw new Error('Invalid institutional destination');
    const info = await transport.sendMail({
      from: { name: 'CIRC 2027', address: config.from }, to,
      subject: 'CIRC 2027 — Código de validação ULS Coimbra',
      text: `O seu código de validação ULS Coimbra é: ${code}\n\nEste código é válido durante 10 minutos e só pode ser utilizado uma vez.\nIntroduza-o na página de inscrição do CIRC 2027 onde iniciou o pedido. Não partilhe este código.\n\nSe não pediu esta validação, ignore esta mensagem.\nCIRC 2027 · https://circ-coimbra.org`,
      disableFileAccess: true, disableUrlAccess: true,
    });
    if (!info.accepted?.length) throw new Error('Delivery not accepted');
  };
}

async function requireAccount(request) {
  if (!enabled.value()) throw new HttpsError('unavailable', 'A validação institucional ainda não está disponível.');
  if (!request.auth?.uid) throw new HttpsError('unauthenticated', 'Inicie sessão para continuar.');
  if (request.auth.token.email_verified !== true) throw new HttpsError('failed-precondition', 'Confirme primeiro o email da sua conta.');
  // Reject disabled/deleted accounts and tokens revoked since their authentication time.
  let account;
  try { account = await getAuth().getUser(request.auth.uid); }
  catch { throw new HttpsError('unauthenticated', 'Volte a iniciar sessão.'); }
  const revokedAfter = Date.parse(account.tokensValidAfterTime || '') || 0;
  if (account.disabled || !account.emailVerified || Number(request.auth.token.auth_time || 0) * 1000 < revokedAfter) {
    throw new HttpsError('unauthenticated', 'Volte a iniciar sessão.');
  }
  const allowed = new Set(String(pilotEmails.value() || '').split(',')
    .map((email) => email.trim().toLowerCase()).filter(Boolean));
  const accountEmail = typeof account.email === 'string' ? account.email.trim().toLowerCase() : '';
  if (!accountEmail || !allowed.has(accountEmail)) {
    throw new HttpsError('permission-denied', 'A validação institucional está limitada às contas autorizadas para o piloto.');
  }
  return request.auth.uid;
}

async function handle(request, action) {
  const uid = await requireAccount(request);
  if (!request.data || typeof request.data !== 'object' || Array.isArray(request.data)) {
    throw new HttpsError('invalid-argument', 'Pedido inválido.');
  }
  try {
    const service = createVerificationService({ store, secret: otpSecret.value(),
      sendCode: action === 'request' ? mailSender() : undefined });
    return action === 'request'
      ? await service.requestCode({ uid, mec: request.data.mec, ip: request.rawRequest.ip || 'unknown' })
      : await service.verifyCode({ uid, challengeId: request.data.challengeId, code: request.data.code });
  } catch (error) {
    if (error instanceof HttpsError) throw error;
    if (error instanceof VerificationError) throw new HttpsError(error.code, error.message);
    // Do not log data, codes, SMTP secrets, or raw provider errors.
    throw new HttpsError('unavailable', 'Não foi possível concluir a validação. Tente novamente mais tarde.');
  }
}

exports.requestUlsVerification = onCall({ ...options, secrets: [otpSecret, smtpSecret] }, (request) => handle(request, 'request'));
exports.verifyUlsVerification = onCall({ ...options, secrets: [otpSecret] }, (request) => handle(request, 'verify'));
