import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { loadStudentProof, submitStudentVerification, withdrawStudentVerification } from '../../auth/studentVerificationStore';
import StudentVerification from './StudentVerification';
jest.mock('../../auth/studentVerificationStore', () => ({ loadStudentProof: jest.fn(), submitStudentVerification: jest.fn(), withdrawStudentVerification: jest.fn() }));
const user = { uid: 'student', emailVerified: true };
const ready = { status: 'ready', profileName: 'Maria Leonor de Sá', approved: false };
function show(verification = ready, account = user) { return render(<MemoryRouter><StudentVerification user={account} verification={verification} /></MemoryRouter>); }
beforeEach(() => { jest.clearAllMocks(); URL.createObjectURL = jest.fn(() => 'blob:private-proof'); URL.revokeObjectURL = jest.fn(); });
test('requires email verification before offering a document form', () => {
  show(ready, { ...user, emailVerified: false });
  expect(screen.getByText(/Confirme o email da sua conta/)).toBeInTheDocument();
  expect(screen.queryByLabelText('Comprovativo de matrícula')).not.toBeInTheDocument();
});
test('submits school and a checked document without asking for course or age', async () => {
  submitStudentVerification.mockResolvedValue();
  const { unmount } = show();
  expect(screen.getByText(/Sem limite de idade/)).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Escola / instituição'), { target: { value: 'Escola de Saúde' } });
  expect(screen.queryByLabelText('Curso')).not.toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Comprovativo de matrícula'), { target: { files: [new File(['%PDF-1.4\n'], 'document.pdf', { type: 'application/pdf' })] } });
  const check = await screen.findByRole('checkbox');
  expect(screen.getByText('Ficheiro preparado. Falta enviar para análise.')).toBeInTheDocument();
  expect(submitStudentVerification).not.toHaveBeenCalled();
  expect(screen.getByRole('button', { name: 'Enviar para análise' })).toBeDisabled();
  fireEvent.click(check);
  fireEvent.click(screen.getByRole('button', { name: 'Enviar para análise' }));
  await waitFor(() => expect(submitStudentVerification).toHaveBeenCalledWith({ school: 'Escola de Saúde', proof: { mimeType: 'application/pdf', base64: 'JVBERi0xLjQK' } }));
  expect(await screen.findByText('Comprovativo enviado. Aguarde a análise pelo secretariado.')).toBeInTheDocument();
  unmount();
  expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:private-proof');
});
test('shows pending, correction, approval and changed-name states', () => {
  const data = { school: 'Escola de Saúde', course: 'IMR', status: 'pending' };
  const { rerender } = show({ ...ready, data });
  expect(screen.getByText('Comprovativo em análise')).toBeInTheDocument();
  expect(screen.queryByLabelText('Comprovativo de matrícula')).not.toBeInTheDocument();
  rerender(<MemoryRouter><StudentVerification user={user} verification={{ ...ready, data: { ...data, status: 'correction', reviewNote: 'Falta o ano letivo.' } }} /></MemoryRouter>);
  expect(screen.getByText('Falta o ano letivo.')).toBeInTheDocument();
  expect(screen.getByLabelText('Comprovativo de matrícula')).toBeInTheDocument();
  rerender(<MemoryRouter><StudentVerification user={user} verification={{ ...ready, approved: true, data: { ...data, status: 'approved' } }} /></MemoryRouter>);
  expect(screen.getByText('Tarifa de estudante aprovada')).toBeInTheDocument();
  rerender(<MemoryRouter><StudentVerification user={user} verification={{ ...ready, nameChanged: true, data: { ...data, status: 'approved' } }} /></MemoryRouter>);
  expect(screen.getByText('Nome do perfil alterado: é necessária nova análise')).toBeInTheDocument();
  expect(screen.queryByText('Tarifa de estudante aprovada')).not.toBeInTheDocument();
});
test('withdrawal requires explicit confirmation', async () => {
  withdrawStudentVerification.mockResolvedValue();
  show({ ...ready, data: { school: 'Escola', course: 'IMR', status: 'pending' } });
  fireEvent.click(screen.getByRole('button', { name: 'Retirar pedido e apagar comprovativo' }));
  expect(withdrawStudentVerification).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: 'Confirmar remoção' }));
  await waitFor(() => expect(screen.queryByRole('button', { name: 'Confirmar remoção' })).not.toBeInTheDocument());
  expect(withdrawStudentVerification).toHaveBeenCalledTimes(1);
});
test('dragging one file prepares it, while removing it or dropping several cannot submit', async () => {
  show();
  const file = new File(['%PDF-1.4\n'], 'matricula.pdf', { type: 'application/pdf' });
  const dropzone = screen.getByRole('group', { name: 'Upload do comprovativo' });
  fireEvent.drop(dropzone, { dataTransfer: { files: [file] } });
  await screen.findByRole('checkbox');
  expect(screen.getByText('matricula.pdf')).toBeInTheDocument();
  expect(submitStudentVerification).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: 'Remover ficheiro selecionado' }));
  expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Enviar para análise' })).toBeDisabled();
  fireEvent.drop(dropzone, { dataTransfer: { files: [file, file] } });
  expect(screen.getByRole('alert')).toHaveTextContent('Envie um ficheiro de cada vez.');
  expect(submitStudentVerification).not.toHaveBeenCalled();
});
test('a failed upload retains the prepared file for retry and never claims receipt', async () => {
  submitStudentVerification.mockRejectedValueOnce({ code: 'unavailable' }).mockResolvedValueOnce();
  show();
  fireEvent.change(screen.getByLabelText('Escola / instituição'), { target: { value: 'Escola de Saúde' } });
  fireEvent.change(screen.getByLabelText('Comprovativo de matrícula'), { target: { files: [new File(['%PDF-1.4\n'], 'matricula.pdf', { type: 'application/pdf' })] } });
  fireEvent.click(await screen.findByRole('checkbox'));
  fireEvent.click(screen.getByRole('button', { name: 'Enviar para análise' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('O envio não foi confirmado.');
  expect(screen.queryByText('Comprovativo recebido')).not.toBeInTheDocument();
  expect(screen.queryByText('Comprovativo enviado. Aguarde a análise pelo secretariado.')).not.toBeInTheDocument();
  expect(screen.getByText('matricula.pdf')).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Enviar para análise' }));
  expect(await screen.findByText('Comprovativo enviado. Aguarde a análise pelo secretariado.')).toBeInTheDocument();
  expect(submitStudentVerification).toHaveBeenCalledTimes(2);
});
test('a saved request can open its private uploaded file only on demand', async () => {
  loadStudentProof.mockResolvedValue({ mimeType: 'application/pdf', base64: 'JVBERi0xLjQK' });
  show({ ...ready, data: { school: 'Escola', status: 'pending', proofAvailable: true, revision: 2 } });
  expect(screen.getByText('Comprovativo recebido')).toBeInTheDocument();
  expect(loadStudentProof).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: 'Ver comprovativo enviado' }));
  const link = await screen.findByRole('link', { name: /Descarregar comprovativo/ });
  expect(link).toHaveAttribute('href', 'blob:private-proof');
  expect(loadStudentProof).toHaveBeenCalledWith({ id: user.uid, revision: 2 });
  fireEvent.click(screen.getByRole('button', { name: 'Fechar comprovativo' }));
  expect(screen.queryByRole('link', { name: /Descarregar comprovativo/ })).not.toBeInTheDocument();
  expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:private-proof');
});
